// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3V6AmdT6Tyka-zHcX8KNHlt2l06OvNY4',
    appId: '1:17948412483:web:91f6f89cb10719b7bf22f6',
    messagingSenderId: '17948412483',
    projectId: 'authtutorial-6e282',
    authDomain: 'authtutorial-6e282.firebaseapp.com',
    storageBucket: 'authtutorial-6e282.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUJmqndgvm98ZlQgMUTwrkorQISaUucm0',
    appId: '1:17948412483:android:4418a6bb61189faabf22f6',
    messagingSenderId: '17948412483',
    projectId: 'authtutorial-6e282',
    storageBucket: 'authtutorial-6e282.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDaeGpp0Yr_HIHKRxIXbBGaNewi80YihI',
    appId: '1:17948412483:ios:e7dc66a1330f403cbf22f6',
    messagingSenderId: '17948412483',
    projectId: 'authtutorial-6e282',
    storageBucket: 'authtutorial-6e282.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDaeGpp0Yr_HIHKRxIXbBGaNewi80YihI',
    appId: '1:17948412483:ios:e7dc66a1330f403cbf22f6',
    messagingSenderId: '17948412483',
    projectId: 'authtutorial-6e282',
    storageBucket: 'authtutorial-6e282.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3V6AmdT6Tyka-zHcX8KNHlt2l06OvNY4',
    appId: '1:17948412483:web:2c557a7d270bca9fbf22f6',
    messagingSenderId: '17948412483',
    projectId: 'authtutorial-6e282',
    authDomain: 'authtutorial-6e282.firebaseapp.com',
    storageBucket: 'authtutorial-6e282.appspot.com',
  );
}
